name: Summary CI
on:
  schedule:
    - cron: "0 1 * * *"
  repository_dispatch:
    types:
      - summary
  workflow_dispatch:
jobs:
  release:
    name: Check status
    runs-on: ubuntu-latest
    steps:
      - uses: upptime/uptime-monitor@master
        with:
          command: "readme"
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
